Missing comma after options: {} in example
Results in the following error when running Grunt:
```
src: '*.html', // Files to perform replacements and includes with
                        ^^^
Loading "Gruntfile.js" tasks...ERROR
>> SyntaxError: Unexpected identifier
```